# config.yaml

HOME_DIR: /home/sig/files/VideoAnalyticsFramework/
# DO NOT OMIT the last slash for directories

edge:
  host: '127.0.0.1'
  port: 6666
  video_config:
    src_path: 'dataset/uav/'
    resize: 0.5
    fps: 10
    read_start: 30
    max_num: 150
    batch_size: 1
  codecs: 'png'
  qfactor: 95 # only valid for jpg
  log_dir: null
  log_name: null

cloud:
  host: '127.0.0.1'
  port: 7777
  gt_dir: 'ground_truth/'
  gt_ckpt_path: 'models/yolov8n.pt'
  infer_ckpt_path: 'models/yolov8n.pt'
  show_image: True


